spring:
  datasource:
    url: jdbc:h2:mem:todosdb
    username: todos
    password: todos
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true


management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /internal
  endpoint:
    health:
      enabled: true
      show-details: always